# src/core/stat_constants.py
"""属性常量定义"""

# 基础属性ID
STAT_HP = 111
STAT_ATK = 121
STAT_DEF = 131
STAT_IMPACT = 122
STAT_CRIT_RATE = 201
STAT_CRIT_DMG = 211
STAT_ANOMALY_MASTERY = 314
STAT_PENETRATION = 231

# ExtraLevel 属性ID
EXTRA_HP = 11101
EXTRA_ATK = 12101
EXTRA_IMPACT = 12201
EXTRA_CRIT_RATE = 20101
EXTRA_CRIT_DMG = 21101
EXTRA_ANOMALY_MASTERY = 31401
EXTRA_PENETRATION = 23101

# 属性映射
EXTRA_TO_BASE_MAPPING = {
    EXTRA_HP: STAT_HP,
    EXTRA_ATK: STAT_ATK,
    EXTRA_IMPACT: STAT_IMPACT,
    EXTRA_CRIT_RATE: STAT_CRIT_RATE,
    EXTRA_CRIT_DMG: STAT_CRIT_DMG,
    EXTRA_ANOMALY_MASTERY: STAT_ANOMALY_MASTERY,
    EXTRA_PENETRATION: STAT_PENETRATION
}